pulp_default_admin_password: password
pulp_install_plugins:
  # pulp-ansible: {}
  # pulp-certguard: {}
  # pulp-cookbook: {}
  # pulp-deb: {}
  # pulp-docker: {}
  # pulp-gem: {}
  # pulp-maven: {}
  # pulp-python: {}
  # pulp-rpm:
  #   prereq_role: "/home/vagrant/devel/pulp-rpm-prerequisites"
  pulp-file: {}
pulp_settings:
  secret_key: "unsafe_default"
