---
- hosts: all
  vars:
    paths_to_vars_files:
      - '../local.dev-config.yml'
      - '../example.dev-config.yml'
  pre_tasks:
    - include_vars: "{{ item }}"
      with_first_found: "{{ paths_to_vars_files }}"
    - name: Set up Vagrant machine for source installs
      include: ../vagrant/vagrant-pretask.yml
  roles:
    - pulp-database
    - pulp-workers
    - pulp-resource-manager
    - pulp-webserver
    - pulp-content
    - pulp-devel
  environment:
    DJANGO_SETTINGS_MODULE: pulpcore.app.settings
