---
- hosts: all
  vars:
    paths_to_vars_files:
      - '../local.user-config.yml'
      - '../example.user-config.yml'
  pre_tasks:
    - include_vars: "{{ item }}"
      with_first_found: "{{ paths_to_vars_files }}"

  roles:
    - pulp-database
    - pulp-workers
    - pulp-resource-manager
    - pulp-webserver
    - pulp-content
  environment:
    DJANGO_SETTINGS_MODULE: pulpcore.app.settings
